char* Altair_8800_text = "The Altair 8800 is a^micro-computer designed^in 1974 by MITS and based^on the Intel 8080 CPU.^The designers hoped to^sell a few hundred build-^it-yourself kits to^hobbyists, and were^surprised when they sold^thousands in the first month.^The Altair also appealed to^individuals and businesses^that just wanted a computer^and purchased the assembled^version. The Altair is widely^recognized as the spark that^ignited the microcomputer^revolution as the first^commercially successful^personal computer.";
char* Amiga_500_text = "The Amiga 500, also known as^the A500, is the first low-^end Commodore Amiga 16/32-bit^multimedia home/personal^computer. It was announced at^the winter Consumer Electro-^nics Show in January 1987.^Graphics can be displayed in^multiple resolutions and^color depths, even on the^same screen. The system uses^planar graphics, with up to^five bitplanes (four in high^resolution) allowing 2-, 4-,^8-, 16-, and 32-color^screens, from a palette of^4096 colors.^";
char* Apple_II_text = "The Apple II, stylized as^apple ][, is an 8-bit home^computer, one of the first^highly successful mass-^produced microcomputer^products, designed primarily^by Steve Wozniak (Steve Jobs^oversaw the development of^the Apple II's foam-molded^plastic case and Rod Holt^developed the switching power^supply). It was introduced in^1977 at the West Coast^Computer Faire by Jobs and^was the first consumer^product sold by Apple^Computer. Along with the^PET 2001 and the TRS-80,^Byte magazine referred to^these as the ''1977 Trinity''^of personal computing.^";
char* Apple_Lisa_text = "Apple Lisa was a desktop^computer developed by Apple,^released on January 19, 1983.^It was one of the first^personal computers to offer^a graphical user interface^in a machine aimed at^individual business users.^Development of the Lisa began^in 1978, and it underwent^many changes during the^development period before^shipping at the very high^price of US$9,995 with a 5^MB hard drive. The high^price, relatively low^performance and unreliable^'Twiggy' floppy disks led to^poor sales, with only^100,000 units sold.^";
char* Apple_Macintosh_text = "The Macintosh is a series^of personal computers^designed, developed, and^marketed by Apple Inc.^Steve Jobs introduced^the original Macintosh^computer on January 10,^984. This was the^company's first mass-market^personal computer featuring^an integral graphical user^interface and mouse.^This first model was later^renamed to 'Macintosh 128k'^for uniqueness amongst a^populous family of sub-^sequently updated models^which are also based on^Apple's same proprietary^architecture. Since 1998,^Apple has largely phased^out the Macintosh name^in favor of 'Mac', though^the product family has^been nicknamed 'Mac' or^'the Mac' since the^development of the first^model.^";
char* BBC_Micro_text = "The BBC Microcomputer System,^or BBC Micro, is a series of^microcomputers and associated^peripherals designed and built^by the Acorn Computer company^for the BBC Computer Literacy^Project, operated by the^British Broadcasting^Corporation. Designed with an^emphasis on education, it was^notable for its ruggedness,^expandability, and the^quality of its operating^system.^";
char* C128_text = "The Commodore 128, also known^as the C128, C-128, C= 128,^or occasionally CBM 128, is^the last 8-bit home computer^that was commercially^released by Commodore^Business Machines (CBM).^Introduced in January 1985^at the CES in Las Vegas,^it appeared three years^after its predecessor,^the bestselling Commodore 64.^";
char* C64_text = "The Commodore 64, also known^as the C64, C-64, C= 64, or^occasionally CBM 64 or VIC-64^in Sweden, is an 8-bit home^computer introduced in^January 1982 by Commodore^International. It is listed^in the Guinness World Records^as the highest-selling single^computer model of all time,^with independent estimates^placing the number sold^between 10 and 17 million^units. Volume production^started in early 1982,^marketing in August for^US$595. Preceded by the^Commodore VIC-20 and^Commodore PET, the C64 took^its name from its 64^kilobytes of RAM.^";
char* EpsonPX_text = "The Epson PX-8 aka Geneva^was a small laptop computer^made by the Epson^Corporation in the mid-1980s.^It had a Z-80 compatible^micro-processor, and ran a^customized version of the^CP/M-80 operating system^as well as various^applications from a pair of^ROM cartridge slots which^were treated as drives.^For file storage it had a^built-in microcassette drive.^The PX-8 did not have any^internal disk drive, and^instead allowed either memory^to be partitioned into^application memory and a RAM^disk, or an external 60 KB^or 120 KB intelligent RAM^disk module to be attached^(64K and 128K internally but^some used for the^processor). The intelligent^RAM disk module had its own^Z80 processor with a backup^battery.^";
char* HP200_text = "The HP 200LX (F1060A, F1061A,^F1216A), also known as^project Felix, is a^personal digital^assistant introduced by^Hewlett-Packard in 1994.^It was often called a Palmtop^PC, and it was notable that^it was, with some minor^exceptions, a MS-DOS-^compatible computer^in a palmtop format,^complete with a monochrome^graphic display, QWERTY^keyboard, serial port,^and PCMCIA expansion slot.^";
char* IMSAI8080_text = "The IMSAI 8080 was an early^microcomputer released in^late 1975, based on the Intel^8080 and later 8085 and^S-100 bus. It was a^clone of its main competitor,^the earlier MITS Altair 8800.^The IMSAI is largely regarded^as the first 'clone'^microcomputer. The IMSAI^machine ran a highly modified^version of the CP/M operating^system called IMDOS.^It was developed,^manufactured and sold by^IMS Associates, Inc.^(later renamed IMSAI^Manufacturing Corp). In^total, between 17,000 and^20,000 units were produced^from 1975 to 1978.^";
char* JUPITER_ACE_text = "The Jupiter Ace was a British^home computer of the early^1980s. It was produced by the^company Jupiter Cantab which^as set up for the purpose.^The Ace differed from other^microcomputers of the time^in that it used Forth^instead of the more popular^BASIC. After Jupiter Cantab^ceased trading, the brand^was acquired by Boldfield^Computing Ltd in 1984,^before eventually being^sold to Andrews UK Limited^in 2015 (the company^owned by Paul Andrews, who^also conceived the Sinclair^Spectrum ZX Vega games^console).^";
char* KIM1_text = "The KIM-1, short for Keyboard^Input Monitor, was a small^6502-based single-board^computer developed and^produced by MOS Technology,^Inc. and launched in 1976.^It was very successful in^that period, due to its low^price (following from the^inexpensive 6502) and easy-^access expandability.^";
char* Lilith1_text = "Lilith is the name of a^custom built workstation^using the AMD 2901 bit-slice^processor by the group of^Niklaus Wirth at ETH Zuerich.^The project started in^1977 and by 1984 several^hundred workstations were^in use. It had a high^resolution full page^display, a mouse, a laser^printer interface, and a^network interface.^Its software was written^completely in Modula-2 and^included a relational^database program called^Lidas.^";
char* ORIC1_text = "Based on a MOS 1 MHz 6502A^CPU, the Oric-1 came in 16^KB or 48 KB RAM variants^for 129 and 169 GBP^respectively, matching the^models available for the^popular ZX Spectrum and^undercutting the price of^the 48 KB version of the^Spectrum by a few pounds.^The '48 KB' Oric-1 version^was actually 64 KB. The top^16 KB of memory are masked^by the BASIC ROM and thus^normally not available for^the user; The optional disc^drive unit contains some^additional hardware that^allows it to enable or^disable the ROM, effectively^adding 16 KB of RAM to the^machine.^";
char* PDP11_text = "The PDP-11 is a series of^16-bit minicomputers sold^by Digital Equipment^Corporation (DEC) from^1970 into the 1990s, one^of a succession of^products in the PDP^series. The PDP-11 had^several uniquely innovative^features, and was easier to^program than its predecessors^through the additional^general-purpose registers.^The PDP-11 replaced the PDP-8^in many real-time applications,^although both product lines^lived in parallel for more^than 10 years. In total,^around 600,000 PDP-11s of all^models were sold, making it^one of DEC's most successful^product lines.";
char* PDP8_text = "The 12-bit PDP-8, produced by^Digital EquipmentCorporation^(DEC), was the first^successful commercial^minicomputer. DEC introduced^it on March 22, 1965 priced^at $18,500 (equivalent to^about $140,000 in 2015) and^eventually sold more than^50,000 systems, the most^of any computer up to that^time. The PDP-8 was the^first computer to be sold^for under $20,000 and then^DEC sold the PDP-8/S for^under $10,000. It was the^first widely sold computer^in the DEC PDP series of^computers (the PDP-5 was^not originally intended^to be a general-purpose^computer).^";
char* PET2001_text = "The Commodore PET (Personal^Electronic Transactor) is a^line of home/personal^computers produced starting^in 1977 by Commodore^International. A top-seller^in the Canadian and United^States educational markets,^it was Commodore's first^full-featured computer,^and formed the basis for^their entire 8-bit product^line, including the^Commodore 64. The first^model, which was named^the PET 2001, was the^first personal computer ever^made available to retail^consumers.^";
char* PLUS4_text = "The Commodore Plus/4 is a^home computer released by^Commodore International in^1984. The 'Plus/4' name refers^to the four-application ROM^resident office suite (word^processor, spreadsheet,^database, and graphing);^it was billed as 'the^productivity computer with^software built-in'.^Internally, the Plus/4^shares the same basic^architecture as the lower-^end Commodore 16 and 116^models, and is able to use^software and peripherals^designed for them. However,^it is not compatible with^the well-established Commodore^64. While the Plus/4 had some^success in Europe, it was a^failure in the United States,^where it was derided as the^'Minus/60'.^";
char* PONG_text = "Pong is one of the earliest^arcade video games and the^very first sports arcade^video game. It is a table^tennis sports game featuring^simple two-dimensional^graphics. While other arcade^video games such as Computer^Space came before it, Pong^was one of the first video^games to reach mainstream^popularity. The aim is to^defeat an opponent in a^simulated table-tennis game^by earning a higher score.^The game was originally^manufactured by Atari,^which released it in 1972.^Allan Alcorn created Pong^as a training exercise^assigned to him by Atari^co-founder Nolan Bushnell.^";
char* TI994a_text = "The Texas Instruments^TI-99/4A is a home computer,^released June 1981 in the^United States at a price^of $525 ($1,369 adjusted^for inflation). It is an^enhanced version of the^less successful TI-99/4^model, which was released^in late 1979 at a price^of $1,150 ($3,756 adjusted^for inflation). The^TI-99/4 had a calculator-^style chiclet keyboard^and a character set that^lacked lowercase text.^The TI-99/4A added an^additional graphics mode,^'lowercase' characters^consisting of small^capitals, and a full-travel^keyboard. Both used 16-bit^processors, making the^TI-99/4 series the first^16-bit home computers.^";
char* ZX81_text = "The ZX81 is a home computer^produced by Sinclair Research^and manufactured in Scotland^by Timex Corporation. It was^launched in the United^Kingdom in March 1981 as^the successor to Sinclair's^ZX80 and was designed to be^a low-cost introduction to^home computing for the^general public. It was^hugely successful, and more^than 1.5 million units were^sold before it was^discontinued. The ZX81^found commercial success^in many other countries,^notably the United States,^where it was initially sold^as the ZX-81. Timex^manufactured and distributed^it under licence and enjoyed^a substantial but brief^boom in sales. Timex later^produced its own versions^of the ZX81 for the US market.^Unauthorised clones of the^ZX81 were produced in^several countries.^";
struct exhibit exhibits[] = {
{0x45, 16, 10240, 0, 0, 0, &Altair_8800_text }, 
{0x45, 12, 8192, 10240, 0, 32, &Amiga_500_text }, 
{0x45, 20, 12288, 18432, 0, 64, &Apple_II_text }, 
{0x45, 20, 12288, 30720, 0, 96, &Apple_Lisa_text }, 
{0x45, 20, 12288, 43008, 0, 128, &Apple_Macintosh_text }, 
{0x45, 16, 10240, 55296, 0, 160, &BBC_Micro_text }, 
{0x46, 16, 10240, 0, 0, 192, &C128_text }, 
{0x46, 12, 8192, 10240, 0, 224, &C64_text }, 
{0x46, 16, 10240, 18432, 0, 256, &EpsonPX_text }, 
{0x46, 16, 10240, 28672, 0, 288, &HP200_text }, 
{0x46, 16, 10240, 38912, 0, 320, &IMSAI8080_text }, 
{0x46, 12, 8192, 49152, 0, 352, &JUPITER_ACE_text }, 
{0x46, 12, 8192, 57344, 0, 384, &KIM1_text }, 
{0x47, 16, 10240, 0, 0, 416, &Lilith1_text }, 
{0x47, 20, 12288, 10240, 0, 448, &ORIC1_text }, 
{0x47, 20, 12288, 22528, 0, 480, &PDP11_text }, 
{0x47, 16, 10240, 34816, 0, 512, &PDP8_text }, 
{0x47, 16, 10240, 45056, 0, 544, &PET2001_text }, 
{0x47, 16, 10240, 55296, 0, 576, &PLUS4_text }, 
{0x48, 16, 10240, 0, 0, 608, &PONG_text }, 
{0x48, 12, 8192, 10240, 0, 640, &TI994a_text }, 
{0x48, 12, 8192, 18432, 0, 672, &ZX81_text }, 
};
